# Journal Finder - Data Mining Final Project

This notebook demonstrates the instructor-required pipeline:

1. Load the cleaned computer science article dataset
2. Inspect the extracted journals and article counts
3. Build a top-5 journal recommender from article abstracts and metadata
4. Run a sample query abstract
5. Measure a simple `Hit@5` score
6. Inspect topic clusters

In [1]:
import sys
from pathlib import Path

import pandas as pd

ROOT = Path.cwd().parent
sys.path.append(str(ROOT / "src"))

from recommender import JournalRecommender
from evaluation import hit_at_k

DATA_PATH = ROOT / "outputs" / "base_articles_clean.csv"
df = pd.read_csv(DATA_PATH)
print("Rows:", len(df))
print("Unique journals:", df["journal_name"].nunique())
df.head(3)

Rows: 7694
Unique journals: 175

,record_id,title,abstract_text,journal_name,pub_year,subject_terms,keyword_terms,keyword_plus_terms,title_clean,abstract_clean,subject_terms_clean,keyword_terms_clean,keyword_plus_terms_clean,clean_token_count,model_text,model_token_count
0,88657,Searching in metric spaces,<p>The problem of searching the elements of a ...,ACM COMPUTING SURVEYS,2001,"Computer Science, Theory & Methods,Computer Sc...","algorithms,curse of dimensionality,nearest nei...","NEAREST-NEIGHBOR SEARCH,TREES,FILE,ALGORITHM,Q...",searching metric spaces,problem searching elements set close given que...,computer science theory methodscomputer science,algorithmscurse dimensionalitynearest neighbor...,nearestneighbor searchtreesfilealgorithmquerie...,115,searching metric spaces problem searching elem...,245
1,88661,A survey of rollback-recovery protocols in mes...,<p>This survey covers rollback-recovery techni...,ACM COMPUTING SURVEYS,2002,"Computer Science, Theory & Methods,Computer Sc...","design,reliability,performance,message logging...","PREVENTING USELESS CHECKPOINTS,DISTRIBUTED SYS...",survey rollbackrecovery protocols messagepassi...,survey covers rollbackrecovery techniques requ...,computer science theory methodscomputer science,designreliabilityperformancemessage loggingrol...,preventing useless checkpointsdistributed syst...,73,survey rollbackrecovery protocols messagepassi...,163
2,88666,The many faces of publish/subscribe,<p>Well adapted to the loosely coupled nature ...,ACM COMPUTING SURVEYS,2003,"Computer Science, Theory & Methods,Computer Sc...","design,distribution,interaction,publish/subscribe","MULTICAST,INFRASTRUCTURE,SYSTEMS,DESIGN",many faces publishsubscribe,well adapted loosely coupled nature distribute...,computer science theory methodscomputer science,designdistributioninteractionpublishsubscribe,multicastinfrastructuresystemsdesign,83,many faces publishsubscribe well adapted loose...,176

In [2]:
df[["journal_name", "pub_year"]].describe(include="all")

                          journal_name     pub_year
count                             7694  7694.000000
unique                             175          NaN
top     IEEE TRANSACTIONS ON COMPUTERS          NaN
freq                                76          NaN
mean                               NaN  2010.150897
std                                NaN     5.227314
min                                NaN  2000.000000
25%                                NaN  2006.000000
50%                                NaN  2011.000000
75%                                NaN  2015.000000
max                                NaN  2018.000000

In [3]:
df["journal_name"].value_counts().head(10)

journal_name
IEEE TRANSACTIONS ON COMPUTERS                              76
COMPUTER SPEECH AND LANGUAGE                                76
COMPUTING                                                   76
JOURNAL OF PARALLEL AND DISTRIBUTED COMPUTING               76
MATHEMATICAL AND COMPUTER MODELLING OF DYNAMICAL SYSTEMS    76
JOURNAL OF COMPUTER SCIENCE AND TECHNOLOGY                  75
SIAM JOURNAL ON COMPUTING                                   75
COMPUTER SYSTEMS SCIENCE AND ENGINEERING                    75
COMPUTER APPLICATIONS IN ENGINEERING EDUCATION              75
COMPUTER AIDED GEOMETRIC DESIGN                             75
Name: count, dtype: int64

In [4]:
model = JournalRecommender.from_dataframe(df)
print("Model ready")

Model ready

In [5]:
query = """
This study proposes a machine learning based intrusion detection framework
for cloud computing environments using feature selection and ensemble classification.
"""

pd.DataFrame(model.recommend(query, top_k=5))

,rank,journal_name,score_sum,matched_docs,example_title,example_year
0,1,COMPUTERS & SECURITY,1.196549,13,A survey of intrusion detection systems based ...,2017
1,2,COMPUTERS & ELECTRICAL ENGINEERING,0.728594,9,A survey on feature selection methods,2014
2,3,KNOWLEDGE AND INFORMATION SYSTEMS,0.708080,10,Stability of feature selection algorithms: a s...,2007
3,4,COMPUTER SYSTEMS SCIENCE AND ENGINEERING,0.674164,6,An extensive empirical evaluation of classifie...,2017
4,5,NEUROCOMPUTING,0.589424,9,LibD3C: Ensemble classifiers with a clustering...,2014

In [6]:
score = hit_at_k(df, sample_size=300, k=5)
print(f"Hit@5 (sample=300): {score:.4f}")

Hit@5 (sample=300): 0.6667

In [7]:
clusters = pd.read_csv(ROOT / "outputs" / "topic_clusters.csv")
clusters.head(10)

,record_id,journal_name,pub_year,subject_terms,cluster_id
0,88657,ACM COMPUTING SURVEYS,2001,"Computer Science, Theory & Methods,Computer Sc...",0
1,88661,ACM COMPUTING SURVEYS,2002,"Computer Science, Theory & Methods,Computer Sc...",0
2,88666,ACM COMPUTING SURVEYS,2003,"Computer Science, Theory & Methods,Computer Sc...",0
3,88667,ACM COMPUTING SURVEYS,2003,"Computer Science, Theory & Methods,Computer Sc...",3
4,88671,ACM COMPUTING SURVEYS,2004,"Computer Science, Theory & Methods,Computer Sc...",0
5,88674,ACM COMPUTING SURVEYS,2005,"Computer Science, Theory & Methods,Computer Sc...",2
6,88675,ACM COMPUTING SURVEYS,2005,"Computer Science, Theory & Methods,Computer Sc...",0
7,88678,ACM COMPUTING SURVEYS,2006,"Computer Science, Theory & Methods,Computer Sc...",0
8,88681,ACM COMPUTING SURVEYS,2007,"Computer Science, Theory & Methods,Computer Sc...",3
9,88683,ACM COMPUTING SURVEYS,2007,"Computer Science, Theory & Methods,Computer Sc...",0